name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile real_time_emission_parser.py --name RealTimeEmissionParser

      - name: List dist folder contents
        run: dir dist

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: RealTimeEmissionParser
          tag_name: ${{ github.ref_name }}
          files: dist/RealTimeEmissionParser.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
